#!/bin/bash

# SLURM script to run PathoScope v2.0.7 on the simulated metagenomes dataset
# Can be used for full reference database runs or with K12-MG1655 and O157:H7 str. Sakai removed
# Should be ran following the "Running_pathoscope_v2.0.7_pathoMAP_module_array" script
# Ensure logs directory already exists within the current directory before running the SLURM-scheduled script (mkdir -p logs)

#SBATCH --job-name=pathoscope_v2.0.7_simulated_metagenomes_pathoID_array
#SBATCH --output=/path/to/pathoscope_directory/logs/pathoscope_v2.0.7_simulated_metagenomes_pathoID_array_%a.out
#SBATCH --error=/path/to/pathoscope_directory/logs/pathoscope_v2.0.7_simulated_metagenomes_pathoID_array_%a.err
#SBATCH --time=06:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G
#SBATCH -p short
#SBATCH --array=1-54%9 # adjust if you have more or fewer samples (54 in the simulated metagenomes dataset)

# Load the conda environment for PathoScope (adjust the path to your conda installation and environment name)
# See https://github.com/PathoScope/PathoScope for conda enviornment dependencies
source /path/to/conda.sh
conda activate pathoscope

# Make sure output directory exists
mkdir -p /path/to/pathoscope_directory/idOut

# Get the sample name for this array task
SAMPLE_LINE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" simulated_metagenomes.txt) # simulated_metagenomes.txt (provided - see Data Summary) should contain one entry per line, including the relative path to the sample (without _R1/_R2 suffix), e.g., final_metagenomes/HiSeq_20M_K12_50_Sakai_50_rep1
SAMPLE=$(echo "${SAMPLE_LINE}" | tr -d '\r\n\t ')
BASENAME=$(basename "${SAMPLE}")

# Define the path to the SAM file generated by the PathoMAP module for this sample (adjust if your directory structure is different)
MAPDIR="/path/to/pathoscope_directory/simulated_metagenomes/MapOut/${BASENAME}" # adjust if the mapping output directory is different
ALIGN_FILE="${MAPDIR}/${BASENAME}.sam"

# Check if the SAM file exists before running PathoScope ID and exit if it does not
if [[ ! -f "${ALIGN_FILE}" ]]; then
  echo "ERROR: missing SAM -> ${ALIGN_FILE}" >&2
  exit 1
fi

# Create output directory for PathoScope ID results for this sample
OUTDIR="/path/to/pathoscope_directory/idOut/${BASENAME}"
mkdir -p "${OUTDIR}"

# Run PathoScope ID on the SAM file from the PathoMAP module
pathoscope ID \
  -alignFile "${ALIGN_FILE}" \
  -fileType sam \
  -outDir "${OUTDIR}" \
  -expTag "${BASENAME}_minus_K12_Sakai"

### End of script